use_frameworks!

workspace 'VaultSDK'

target 'Example_Swift' do
  
  project 'Example_Swift/Example_Swift'

  pod 'VaultSDK', :path => '../'

  target 'Example_SwiftTests' do
    inherit! :search_paths  
  end

end
