use_frameworks!

workspace 'VaultSDK'

target 'Example_Swift' do
  
  project 'Example_Swift/Example_Swift'

  pod 'VaultSDK', :path => '../'

  target 'Example_SwiftTests' do
    inherit! :search_paths  
  end

end

target 'Example_ObjC' do
  
  project 'Example_ObjC/Example_ObjC'

  pod 'VaultSDK', :path => '../'

  target 'Example_ObjCTests' do
    inherit! :search_paths
  end

end